name: End-to-end MLOps Build pipeline

on:
  workflow_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:      
      - name: Check out repo
        uses: actions/checkout@main
      
      - name: Install az ml extension
        run: az extension add -n ml -y
      
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}      
      
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r ./environment_setup/requirements.txt
          
      - name: Accessing Azure ML Workspace
        uses: Azure/cli@v1
        with:
          inlineScript: python ./aml_code/Workspace.py

          
