name: End-to-end MLOps Build pipeline

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'MLGroup' 
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'ShivaMLservice' 
        type: string
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Check out repo
        uses: actions/checkout@main
      
      - name: Install az ml extension
        run: az extension add -n ml -y
      
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      
      - name: Set Azure ML workspace as default
        run: |
          az configure --defaults group="${{ github.event.inputs.resource_group }}"
          az configure --defaults workspace="${{ github.event.inputs.aml_workspace }}"
      
      - name: Use Python Version 3.6
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: Installing Requirements
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: pip install -r ./environment_setup/requirements.txt
      
      - name: Accessing Azure ML Workspace
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: python ./aml_code/Workspace.py
          
