name: End-to-end MLOps Build pipeline

on:
  workflow_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:      
      - name: Check out repo
        uses: actions/checkout@main
      
      - name: Install az ml extension
        run: az extension add -n ml -y
      
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}      
      
      - name: Use Python Version 3.6
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: Installing Requirements
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: pip install -r ./environment_setup/requirements.txt
      
      - name: Accessing Azure ML Workspace
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: python ./aml_code/Workspace.py
          
