name: Release 

# Controls when the workflow will run
on:

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     
      - uses: actions/checkout@v3
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: spam-artifact
          path: .
      
      - name: install python dependencies
        run: pip install -r ./environment_setup/requirements.txt

              # Runs a set of commands using the runners shell
      - name: Deploy to Azure Container Instance
        run: python ./aml_code/DeployToAci.py
        
      - name: Test ACI Endpoint
        run: python ./aml_code/AciWebserviceTest.py
