name: Release 

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    name: Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
     
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: spam-artifact
          path: .
      
      - name: install python dependencies
        run: pip install -r ./environment_setup/requirements.txt

              # Runs a set of commands using the runners shell
      - name: Deploy to Azure Container Instance
        run: python ./aml_code/DeployToAci.py
        
      - name: Test ACI Endpoint
        run: python ./aml_code/AciWebserviceTest.py
